# simple tmux conf
# i always see options for fancy tmux configs but i'm better off with a simpler approach
# no package manager, no gods, just imperfect beings writing imperfect code
#
# if you want you can use control a as the prefix for tmux. i think the default is fine if you remap caps lock to control tbh
# unbind C-b
# set-option -g prefix C-a


# basic settings
set -g default-terminal "screen-256color"
set -g history-limit 100000
setw -g aggressive-resize on

# use the mouse
set -g mouse on

# use vi key bindings to navigate
set-window-option -g mode-keys vi

# easy pane creation
bind | split-window -h
bind _ split-window -v

# easy pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# window management
set -g base-index 0

# status styling options

# status bar
set -g status-position bottom
set -g status-justify left
set -g status-left ''
set-option -g status-left-length 70


# uncomment and recomment styles to activate. only activate one set at at time

# GITHUB DARK
# ===========
# set -g status-bg "#2F373F"
# set -g status-fg colour15
# # status left options
# set-window-option -g window-status-format '#[bg=default,fg=colour232,bold] #I #W '
# set-window-option -g window-status-current-format '#[bg=colour39,fg=colour235,bold] #I #W '
# # status-right options
# set -g status-right '#[bg=colour39,fg=colour235,bold] %I:%M %p ❐ [#S] '
# set -g status-right-length 70


# WINDOWS XP
# ==========
# that old retro feeling
set -g status-bg colour21
set -g status-fg colour195
# status left options
set-window-option -g window-status-format '#[bold] #I #W '
set-window-option -g window-status-current-format '#[bg=colour34,fg=colour195,bold] #I #W '
# status-right options
set -g status-right '#[bg=colour33,fg=colour195,bold] %I:%M %p ❐ [#S] '
set -g status-right-length 70


# META: reload tmux.conf w/ a shortcut
bind R source-file ~/.tmux.conf \; display-message "    TMUX Config reloaded..".
